fix build for kernel 5.17 const netdev->dev_addr
osdep_service.c:2212:28: error: passing argument 1 of '_rtw_memcpy'
discards 'const' qualifier from pointer target type
[-Werror=discarded-qualifiers]
 2212 |         _rtw_memcpy(pnetdev->dev_addr, padapter->eeprompriv.mac_addr,
ETH_ALEN);

kernel 5.17 adeef3e32146 ("net: constify netdev->dev_addr")
kernel 5.16 f3956ebb3bf0 ("ethernet: use eth_hw_addr_set() instead of ether_addr_copy()")

Signed-off-by: John Thomson <git@johnthomson.fastmail.com.au>